// plane.h
//
// Copyright (C) 2004 by Owen Jacobson
//
// This library is free software; you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation; either version 2.1 of the License, or (at
// your option) any later version.
//
// This library is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
// License (COPYING.txt) for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this library; if not, write to the Free Software Foundation,
// Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// The developer's email is ojacobson@lionsanctuary.net
//

#ifndef NOISE_MODEL_PLANE_H
#define NOISE_MODEL_PLANE_H

#include <assert.h>
#include "../module/modulebase.h"

namespace noise
{

  namespace model
  {
    /// @addtogroup libnoise
    /// @{

    /// @addtogroup models
    /// @{

    /// Model that defines a plane.
    ///
    /// Using a noise module, this class returns values that lie on the
    /// surface of a plane passing through the origin along the @a x and
    /// @a z axes.
    ///
    /// To return a noise value from a point on the sphere, pass the @a x
    /// and @a z coordinates to the GetValue() method.
    ///
    class Plane
    {

      public:

        /// Constructor.
        Plane ();

        /// Constructor, taking the module to draw noise from.
        Plane (const module::Module& module);

        /// Returns the noise module used to generate the values on the plane
        ///
        /// @returns A reference to the noise module.
        ///
        /// @pre A noise module was passed to the SetModule() method.
        const module::Module& GetModule () const
        {
          assert (m_pModule != NULL);
          return *m_pModule;
        }

        /// Returns the noise value at the given position on the plane.
        ///
        /// @param x The @a x coordinate of the point.
        /// @param z The @a z coordinate of the point.
        ///
        /// @returns The noise value.
        ///
        /// @pre A noise module was passed to the SetModule() method.
        ///
        /// The noise value is generated by the module passed to the
        /// SetModule()method.
        double GetValue (double x, double z) const;

        /// Sets the noise module used to generate the values on the plane
        ///
        /// @param module The noise module.
        ///
        /// The noise module must exist for the lifetime of this object, until
        /// you pass a new module to this method.
        void SetModule (const module::Module& module)
        {
          m_pModule = &module;
        }

      private:

        /// A pointer to the module used to generate the noise values.
        const module::Module* m_pModule;

    };

    /// @}

    /// @}

  }

}

#endif
